name: Auto - Verify & plan branch environment
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: terraform-${{ github.base_ref }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform_verify:
    runs-on: ubuntu-latest
    name: Verify & plan terraform code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform format check
        run: terraform fmt -check -diff -recursive

      - name: Initialize Terraform
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_aws_vpn_gateway_preshared_key1: ${{ secrets.AWS_VPN_GATEWAY_PRESHARED_KEY1 }}
          TF_VAR_aws_vpn_gateway_preshared_key2: ${{ secrets.AWS_VPN_GATEWAY_PRESHARED_KEY2 }}

      - name: Run Terraform Plan
        run: |
          terraform plan -input=false -out plan.tfplan >/dev/null
          terraform show plan.tfplan
          terraform show -no-color -json plan.tfplan > tfplan.json
        env:
          TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_aws_vpn_gateway_preshared_key1: ${{ secrets.AWS_VPN_GATEWAY_PRESHARED_KEY1 }}
          TF_VAR_aws_vpn_gateway_preshared_key2: ${{ secrets.AWS_VPN_GATEWAY_PRESHARED_KEY2 }}

      - name: Run Terraform Change Pull Request Commenter Action
        uses: liatrio/terraform-change-pr-commenter@v1.7.1
        with:
          json-file: 'tfplan.json'
          expand-comment: 'true'
          include-workflow-link: 'true'
